name: Sync Peloton to Garmin
on:
  schedule:
    - cron: "12 */4 * * *"
  workflow_dispatch:
  push: 
    branches:
      - main
jobs:
  justin-p2g:
    name: Justin - Sync Peloton to Garmin
    runs-on: ubuntu-latest
    steps:
      - uses: jdowning/p2g-action@2.3.0
        with:
          PELOTON_EMAIL: ${{ secrets.JUSTIN_PELOTON_EMAIL }}
          PELOTON_PASSWORD: ${{ secrets.JUSTIN_PELOTON_PASSWORD }}
          GARMIN_EMAIL: ${{ secrets.JUSTIN_GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.JUSTIN_GARMIN_PASSWORD }}
  traci-p2g:
    name: Traci - Sync Peloton to Garmin
    runs-on: ubuntu-latest
    steps:
      - uses: jdowning/p2g-action@2.3.0
        with:
          PELOTON_EMAIL: ${{ secrets.TRACI_PELOTON_EMAIL }}
          PELOTON_PASSWORD: ${{ secrets.TRACI_PELOTON_PASSWORD }}
          GARMIN_EMAIL: ${{ secrets.TRACI_GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.TRACI_GARMIN_PASSWORD }}
